### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by UliPlabst** [zposten/gremlin-cosmos#20]
Hi, I would like to use the library and also contribute to it. Can you please commit a license so it is clear wether I can use it?

**Comment by zposten** [comment]
Hi @UliPlabst, I'm happy to hear that!  Gremlin-cosmos is released under the MIT license.  This is indicated [in the package.json](https://github.com/zposten/gremlin-cosmos/blob/8d7b5c9957d326b2a1aef47f3a9adfdb9524fac0/package.json#L8) and also displayed [on NPM](https://www.npmjs.com/package/gremlin-cosmos).

I hope this helps!

**Comment by UliPlabst** [comment]
Ah my bad. Thanks for the reply!
