### ISSUE TITLE
Allow string array to be passed to Query.g.V()

### ISSUE THREAD

**Issue by ryanbyk** [zposten/gremlin-cosmos#5]
In some scenarios it makes sense to query multiple vertices at a time. 

say you had 2 vertices 
vertex 1 : 
```
name: ryan,
id: ryan@iscool.com
```
and vertex 2
```
name: zach,
id: zach@notnotcool.com
```
and a whole bunch of other vertices.  But you only want to add edges to both of these ones at the same time.  One query you could run that would return both vertices in the same query is:
`g.V("ryan@iscool.com","zach@notnotcool.com")`

I think the library should allow for the ability to pass a string [] as well as just a single string.

**Comment by zposten** [comment]
Fixed by #6
